waimai:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: waimai
    username: root
    password: abc8909389
  redis:
    host: remote
    port: 26379
#    database: 5
#    password: 123456
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: ${ali-oss-ak}
    access-key-secret: ${ali-oss-sk}
    bucket-name: waimai-class
  wechat:
    appid: xxx
    secret: yyy
